# Generated by Django 4.0.1 on 2022-01-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackendModel',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Text', models.TextField()),
            ],
        ),
    ]
