# Generated by Django 4.0.1 on 2022-01-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_backendmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backendmodel',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
