# Generated by Django 4.0.1 on 2022-01-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendModels',
            fields=[
                ('Title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
    ]
