# Generated by Django 4.0.1 on 2022-01-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendmodels',
            name='Type',
            field=models.CharField(choices=[('1', 'HTML'), ('2', 'CSS'), ('3', 'JS')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frontendmodels',
            name='Description',
            field=models.FileField(upload_to=''),
        ),
    ]
