# Generated by Django 4.0.1 on 2022-01-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_alter_frontendmodels_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendmodels',
            name='Description',
            field=models.FileField(upload_to=models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JS', 'JS')], max_length=4)),
        ),
    ]
