# Generated by Django 4.0.1 on 2022-01-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_alter_frontendmodels_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendmodels',
            name='Description',
            field=models.TextField(),
        ),
    ]
